# nixpacks.toml

[phases.setup]
# Bring Python + toolchain + ffmpeg + common OpenCV/GUI deps
nixPkgs = [
  "python311",
  "gcc",
  "pkg-config",
  "ffmpeg",
  "glib",
  "libGL",
  "xorg.libXext",
  "xorg.libSM",
  "xorg.libXrender",
  "gtk3"
]

[phases.install]
# 1) upgrade build tooling with verbose logs
# 2) preinstall heavy packages from wheels only (avoid source builds)
# 3) install the rest with verbose logs so we see the exact failure
cmds = [
  "python -m pip install --upgrade pip setuptools wheel -v",
  "python -m pip install --only-binary=:all: -v numpy opencv-python-headless uvloop httptools",
  "python -m pip install --no-cache-dir -v -r requirements.txt"
]

[start]
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000} --proxy-headers"
