# nixpacks.toml

[phases.setup]
# Ensure Python + toolchain + ffmpeg + common OpenCV deps
nixPkgs = [
  "python311",
  "gcc",
  "pkg-config",
  "ffmpeg",
  "glib",
  "libGL",
  "xorg.libXext",
  "xorg.libSM",
  "xorg.libXrender",
  "gtk3"
]
# Create a dedicated virtualenv so pip isn't blocked by PEP 668
cmds = [
  "python -m venv /opt/venv"
]

[phases.install]
# Use the venv's python for ALL installs (avoids 'externally managed' error)
cmds = [
  "/opt/venv/bin/python -m pip install --upgrade pip setuptools wheel -v",
  "/opt/venv/bin/python -m pip install --only-binary=:all: -v numpy opencv-python-headless uvloop httptools",
  "/opt/venv/bin/python -m pip install --no-cache-dir -v -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000} --proxy-headers"
