[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/healthz"   # make sure this matches your FastAPI route
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
